# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python build and test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        
    - name: Build
      run: |
        pip wheel -w dist .
        
    - name: Install
      run: |
        pip install power-system-simulation[dev] --find-links=dist

    - name: Test with pytest
      run: |
        pytest

    - name: Check the format
      run: |
        isort --check .
        black --check .
